#!/bin/bash
# Usage: paasify ssh
# Summary: Open an SSH connection to the OpsManager for a given environment
# Help: Open an SSH connection to the OpsManager for a given environment, which can be useful for applying custom configuration or troubleshooting.
#
#    -n    the name of the environment
#  

source $_PAASIFY_ROOT/share/init-env

while getopts ":n:" opt; do
  case ${opt} in
    n )
      name=$OPTARG
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if [ -z "$name" ]; then
  echo "Error: An environment name must be supplied (-n)"
  exit 1
fi

env_dir=$ENVS_DIR/$name

if [ ! -d "$env_dir" ]; then
  echo "Environment '$name' does not exist"
  exit
fi

state_file=$env_dir/terraform.tfstate

if [ -f $env_dir/remote.tf ]; then
  state_json=$(cd $env_dir && terraform state pull)
elif [ -f "$state_file" ]; then
  state_json=$(cat $state_file)
else
  echo "Terraform state does not exist, have you run 'paasify apply -n $name' ?"
  exit 1
fi

source $_PAASIFY_ROOT/share/om-env

$OM_BIN bosh-env -i $opsman_ssh_key